In [1]:
import ftfy
import pandas as pd
from MrDoc.services.common import plot_histogram_with_binary_data, plot_true_evolution, show_scrollable
from MrDoc.config import paths

In [2]:
datos_gptoss = pd.read_excel(paths.data_output / "df_Full_CUN_V0.2_FINAL.xlsx")
# datos_gptoss_medgemma = pd.read_excel(paths.data_output / "df_OLLAMA_GPTOSS_20B_PLUS_MEDGEMMA_FINAL.xlsx")

datos_gptoss = datos_gptoss.map(lambda x: ftfy.fix_text(x) if isinstance(x, str) else x)
# datos_gptoss_medgemma = datos_gptoss_medgemma.map(lambda x: ftfy.fix_text(x) if isinstance(x, str) else x)

In [4]:
plot_histogram_with_binary_data(df=datos_gptoss, column_name_emb_sim="similarity_predicted_selected_V2", column_name_cie10_sim="tree_5_V2", title="GPT-OSS", y_max=300)
plot_histogram_with_binary_data(df=datos_gptoss, column_name_emb_sim="similarity_predicted_nearest", column_name_cie10_sim="tree_5_V2", title="GPT-OSS", y_max=400)

In [6]:
# plot_histogram_with_binary_data(df=datos_gptoss_medgemma, column_name_emb_sim="similarity_predicted_selected_V2", column_name_cie10_sim="tree_5_V2", title="GPT-OSS + MEDGEMMA", y_max=110)
# plot_histogram_with_binary_data(df=datos_gptoss_medgemma, column_name_emb_sim="similarity_predicted_nearest", column_name_cie10_sim="tree_5_V2", title="GPT-OSS + MEDGEMMA", y_max=110)

In [5]:
plot_true_evolution(datos_gptoss, title="Analisis porcentaje de aciertos")
# plot_true_evolution(datos_gptoss_medgemma, title="GPT-OSS + MEDGEMMA")

# EXTRA

## Tree 3 = **TRUE**

In [12]:
columnas = ["diagnostico_predicted", "CIE10_predicted", "diagnostico_nearest", "CIE10_nearest", "diagnostico_selected", "CIE10_selected", "tree_3"]
# datos_gptoss[(datos_gptoss["tree_1"] == True) & (datos_gptoss["tree_5"] == True)][columnas]
datos_gptoss.loc[[26, 72, 1530]][columnas]

,diagnostico_predicted,CIE10_predicted,diagnostico_nearest,CIE10_nearest,diagnostico_selected,CIE10_selected,tree_3
26,Obesidad,E66.01,"Obesidad, no especificada",E66.9,"Obesidad, no especificada",E66.9,True
72,Sobrepeso,E66.3,Sobrepeso,E66.3,Sobrepeso,E66.3,True
1530,Disminución de los niveles de vitamina D,E55.9,"Carencia de vitamina D, no especificada",E55.9,"Carencia de vitamina D, no especificada",E55.9,True

## Tree 3 = **FALSE** and Tree 5 = **TRUE**

In [13]:
columnas = ["diagnostico_predicted", "CIE10_predicted", "diagnostico_nearest", "CIE10_nearest", "diagnostico_selected", "CIE10_selected", "tree_3", "tree_4", "tree_5"]
show_scrollable(datos_gptoss[(datos_gptoss["tree_1"] == False) & (datos_gptoss["tree_5_V2"] == True) & (datos_gptoss["similarity_predicted_selected"] < 0.2)][columnas])

In [ ]:
columnas = ["diagnostico_predicted", "CIE10_predicted", "diagnostico_nearest", "CIE10_nearest", "diagnostico_selected", "CIE10_selected", "tree_3", "tree_4", "tree_5"]
# datos_gptoss[(datos_gptoss["tree_1"] == False) & (datos_gptoss["tree_5_V2"] == True) & (datos_gptoss["similarity_predicted_selected"] < 0.2)][columnas]
datos_gptoss.loc[[2, 242, 1010]][columnas]

,diagnostico_predicted,CIE10_predicted,diagnostico_nearest,CIE10_nearest,diagnostico_selected,CIE10_selected,tree_3,tree_4,tree_5
2,Bacteriuria asintomática,N32.0,Bacteriuria,R82.71,Bacteriuria,R82.71,False,True,True
242,Melanoma in situ,C43.9,Melanoma in situ de labio,D03.0,"Melanoma in situ, localización no especificada",D03.9,False,True,True
1010,EPOC (familiar),J44.9,Insomnio familiar fatal,A81.83,"Enfermedad pulmonar obstructiva crónica, no es...",J44.9,False,False,True

## Tree 5 = **TRUE**

In [ ]:
columnas = ["diagnostico_predicted", "CIE10_predicted", "diagnostico_nearest", "CIE10_nearest", "diagnostico_selected", "CIE10_selected", "tree_4", "tree_5"]
# datos_gptoss[(datos_gptoss["tree_4"] == False) & (datos_gptoss["tree_5"] == True)][columnas]
datos_gptoss.loc[[499, 635, 709]][columnas]

,diagnostico_predicted,CIE10_predicted,diagnostico_nearest,CIE10_nearest,diagnostico_selected,CIE10_selected,tree_4,tree_5
499,Ansiedad,F41.9,Anencefalia,Q00.0,"Trastorno de ansiedad, no especificado",F41.9,False,True
635,Traumatismo craneoencefálico con pérdida de co...,S06.2,Traumatismo de nervios craneales no especifica...,S04.9XXS,Lesión cerebral traumática difusa con pérdida ...,S06.2X9A,False,True
709,Alergia a pólenes de olivo,J30.1,Estado de alergia a anestésico,Z88.4,Rinitis alérgica debida a polen,J30.1,False,True

## Tree 5 V2 = **TRUE**

In [ ]:
columnas = ["diagnostico_predicted", "CIE10_predicted", "diagnostico_selected", "CIE10_selected", "diagnostico_selected_V2", "CIE10_selected_V2", "tree_5", "tree_5_V2"]
# datos_gptoss[(datos_gptoss["tree_5_V2"] == True) & (datos_gptoss["tree_5"] == False)][columnas]
datos_gptoss.loc[[92, 166, 681, 2063]][columnas]

,diagnostico_predicted,CIE10_predicted,diagnostico_selected,CIE10_selected,diagnostico_selected_V2,CIE10_selected_V2,tree_5,tree_5_V2
92,asma,J45.909,"Asma no especificada, sin complicaciones",J45.909,"Asma no especificada, sin complicaciones",J45.909,False,True
166,Dudosa pancreatitis (1994),K85.9,"Pancreatitis aguda sin necrosis ni infección, ...",K85.90,"Enfermedades de páncreas, no especificadas",K86.9,False,True
681,Ictus (padre),I63.9,"Infarto cerebral, no especificado",I63.9,Historia familiar de ictus,Z82.3,False,True
2063,Tabaquismo leve,F17.2,"Dependencia de nicotina, cigarrillos, sin comp...",F17.210,Consumo de tabaco,Z72.0,False,True

## Tree 5 V2 = **FALSE**

In [7]:
columnas = ["diagnostico_predicted", "CIE10_predicted", "diagnostico_selected", "CIE10_selected", "diagnostico_selected_V2", "CIE10_selected_V2", "tree_5_V2"]
datos_gptoss[(datos_gptoss["tree_5_V2"] == False)][columnas]
# datos_gptoss.loc[[73, 91, 516, 523]][columnas]

,diagnostico_predicted,CIE10_predicted,diagnostico_selected,CIE10_selected,diagnostico_selected_V2,CIE10_selected_V2,tree_5_V2
1,Sedentarismo,Z73.1,Falta de descanso y ocio,Z73.2,Falta de descanso y ocio,Z73.2,False
3,Adenoidectomía,Z87.1,Historia personal de otras afecciones especifi...,Z87.898,Historia personal de otras afecciones especifi...,Z87.898,False
14,Hígado de tamaño normal y contornos lisos con ...,Z00.0,Contacto para reconocimiento médico general de...,Z00.00,Contacto para reconocimiento médico general de...,Z00.00,False
19,"Colonoscopia en 2019, sin anomalías mucosas",Z87.89,Historia personal de otras afecciones especifi...,Z87.898,Lesión primaria por onda expansiva de colon as...,S36.510A,False
20,Hernia lumbar (última en 2004),M42.0,Osteocondrosis del adulto de columna vertebral...,M42.16,"Otros desplazamientos de disco intervertebral,...",M51.26,False
...,...,...,...,...,...,...,...
5427,Intolerancia a Rabeprazol,Z79.1,Otra terapia prolongada (actual) con medicamentos,Z79.899,Otra terapia prolongada (actual) con medicamentos,Z79.899,False
5440,Probable enfermedad por reflujo gastroesofágico,K21.9,Enfermedad por reflujo gastroesofágico con eso...,K21.00,Enfermedad por reflujo gastroesofágico con eso...,K21.00,False
5464,Insuficiencia respiratoria nasal secundaria a ...,J34.1,Tabique nasal desviado,J34.2,Tabique nasal desviado,J34.2,False
5476,Alergia a terramicina,T78.2,"Alergia no especificada, contacto inicial",T78.40XA,"Alergia no especificada, contacto inicial",T78.40XA,False
5478,Ototubaritis,H66.0,Otitis media supurativa aguda sin rotura espon...,H66.001,Otitis media supurativa aguda sin rotura espon...,H66.001,False